# This workflow will check best practices
# For more information see: https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/category/java/bestpractices.xml

name: cerberus best practices

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      run: ./check-with-cerberus.sh
    - name: run cerberus
      run: java -jar cerberus-4.0.jar FPM --files=./src --java-version=8 --language=java --rulesets="category/java/bestpractices.xml"
